### ISSUE TITLE
Investigate collection.js integration

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware-contrib/ng2-json-editor#109] opened 2016-12-09 14:38 UTC
Resolve `Cannot resolve module...` error when trying to install [collection.js]( http://www.collectionsjs.com) in the project.

**Comment by jmartinm** [comment] 2016-12-09 15:22
Once we merge the shortcuts, you can document here what can be improved from that PR by adding, for example the `SortedMap`

**Comment by jmartinm** [comment] 2017-01-09 15:45
Duplicate of https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/131

**Closed by jmartinm** 2017-01-09 15:45 UTC
