### ISSUE TITLE
tabs disappear after clicking on left menu

### ISSUE THREAD

**Issue by michamos** [inveniosoftware-contrib/ng2-json-editor#259] opened 2017-04-19 12:46 UTC
```feature
Feature: Tabs don't disappear when jumping around
    Given I am a logged in
    And I open https://labs.inspirehep.net/editor/holdingpen/619286
    When I click on inspire_categories in the left navigation column
    Then the authors tab is still visible
```

this currently fails :smile:

**Comment by harunurhan** [comment] 2017-04-21 07:43
I couldn't reproduce this in the example, will investigate record-editor to be sure, but probably fixed on previous PRs which aren't released yet.

**Comment by harunurhan** [comment] 2017-11-20 09:58
Closing this since it seems to be fixed.

**Closed by harunurhan** 2017-11-20 09:58 UTC
