### ISSUE TITLE
Pressing <Enter> should not write '\n' in value

### ISSUE THREAD

**Issue by michamos** [inveniosoftware-contrib/ng2-json-editor#237] opened 2017-04-05 11:53 UTC
Currently, when pressing enter after inputting a string value results in an explicit carriage return (`\n`) written in the field. This should not happen.

**Comment by harunurhan** [comment] 2017-04-07 09:49
@michamos This doesn't happen for me, but I am gonna check on firefox to reproduce.

**Comment by harunurhan** [comment] 2017-04-07 12:07
Since we couldn't reproduce it also on firefox, I will close it for the moment.

**Closed by harunurhan** 2017-04-07 12:07 UTC
