### ISSUE TITLE
"Admin Mode" doesn't work properly

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#243] opened 2017-04-10 08:35 UTC
The toggling the checkbox doesn't reflect to UI immediately.

**Comment by jmartinm** [comment] 2017-05-22 08:34
Duplicate of https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/291

**Closed by jmartinm** 2017-05-22 08:34 UTC
Labels: bug
